Models/CodeNamesContext.cs
using System.Collections.Generic;

namespace CodeNamesHelper.Models
{
    public class CodeNamesContext
    {
        public CodeNamesContext()
        {
            BlueTeam = new Team { TeamType = TeamType.Blue };
            RedTeam = new Team { TeamType = TeamType.Red };
            Players = new List<Player>();
        }

        public Team BlueTeam { get; set; }
        public Team RedTeam { get; set; }
        public IList<Player> Players { get; set; }

        public Team GetTeamByType(TeamType type)
        {
            return type == TeamType.Blue ? BlueTeam : RedTeam;
        }

        public Team GetOtherTeamByType(TeamType type)
        {
            return type == TeamType.Blue ? RedTeam : BlueTeam;
        }

        public void ResetTeams()
        {
            BlueTeam = new Team { TeamType = TeamType.Blue };
            RedTeam = new Team { TeamType = TeamType.Red };
        }
    }
}

Models/Player.cs
using System;
using System.Linq;
using System.Threading.Tasks;

namespace CodeNamesHelper.Models
{
    public class Player
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public RoleType Role { get; set; }
    }
}

Models/RoleType.cs
namespace CodeNamesHelper.Models
{
    public enum RoleType
    {
        Master, Agent
    }
}

Models/Team.cs
using System.Collections.Generic;

namespace CodeNamesHelper.Models
{
    public class Team
    {
        public Team()
        {
            Players = new List<Player>();
        }

        public IList<Player> Players { get; set; }
        public TeamType TeamType { get; set; }
    }
}

Models/TeamType.cs
namespace CodeNamesHelper.Models
{
    public enum TeamType
    {
        Red, Blue
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace CodeNamesHelper.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }   

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Controllers/TeamBuilderController.cs
using System;
using System.Linq;
using CodeNamesHelper.Extensions;
using CodeNamesHelper.Models;
using Microsoft.AspNetCore.Mvc;

namespace CodeNamesHelper.Controllers
{
    public class TeamBuilderController : Controller
    {
        private static volatile CodeNamesContext _codeNamesContext = new CodeNamesContext();
        
        public IActionResult Index()
        {
            return View(_codeNamesContext);
        }

        [HttpPost]
        public IActionResult Add(String playerName)
        {
            AddPlayer(playerName);

            return View("Index", _codeNamesContext);
        }

        [HttpGet]
        public IActionResult Generate()
        {
            if (_codeNamesContext.Players.Count <= 3)
            {
                ViewData["Message"] = "You must enter at least 4 players.";
                return View("Index", _codeNamesContext);
            }


            GenerateTeams();

            return View("Index", _codeNamesContext);
        }

        [HttpGet]
        public IActionResult Reset()
        {
            _codeNamesContext = new CodeNamesContext();
            return View("Index", _codeNamesContext);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var playerToDelete = _codeNamesContext.Players.FirstOrDefault(x => x.Id.Equals(id));
            _codeNamesContext.Players.Remove(playerToDelete);
            return View("Index", _codeNamesContext);
        }

        private static void GenerateTeams()
        {
            _codeNamesContext.ResetTeams();
            _codeNamesContext.Players.Shuffle();
            var teamPicker = new Random();
            var pickedTeam = teamPicker.Next(0, 2);
            var teamType = pickedTeam == 0 ? TeamType.Red : TeamType.Blue;

            for (var i = 0; i < _codeNamesContext.Players.Count; i++)
            {
                var isEven = i%2 == 0;
                var teamToAddPlayer = isEven
                    ? _codeNamesContext.GetTeamByType(teamType)
                    : _codeNamesContext.GetOtherTeamByType(teamType);

                var playerToAdd = _codeNamesContext.Players[i];

                playerToAdd.Role = teamToAddPlayer.Players.Count == 0 ? RoleType.Master : RoleType.Agent;

                teamToAddPlayer.Players.Add(playerToAdd);
            }
        }

        private static void AddPlayer(string playerName)
        {
            var lastPlayer = _codeNamesContext.Players.LastOrDefault();

            var newId = 1;
            if (lastPlayer != null)
            {
                newId = lastPlayer.Id + 1;
            }


            var newPlayer = new Player
            {
                Id = newId,
                Name = playerName
            };

            _codeNamesContext.Players.Add(newPlayer);
        }
    }
}

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518007">Gulp</a> and <a href="https://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699562">Add an appsetting in config and access it in app.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run & Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CodeNamesHelper</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CodeNamesHelper</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="TeamBuilder" asp-action="Index">Team Builder</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - CodeNamesHelper</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.3.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

Views/TeamBuilder/Index.cshtml
@using Microsoft.AspNetCore.Server.Kestrel.Internal.Http
@model CodeNamesHelper.Models.CodeNamesContext

@{ViewData["Title"] = "Team Builder"; }
<h2>@ViewData["Title"]</h2>
@if (ViewData["Message"] != null)
{
    <div class="alert alert-danger" role="alert">@ViewData["Message"]</div>
}


<section title="team-builder">
    <form asp-action="Add" method="POST">
        <div class="form-group">
            <label for="playerName">Name</label>
            <input name="playerName" type="text" class="form-control" id="playerName" placeholder="Please enter player name">
        </div>
        <button type="submit" class="btn btn-default">Add</button>
    </form>

    @if (Model.Players.Any())
    {
        <div>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Players)
                {
                        <tr>
                            <td>
                                @item.Id
                            </td>
                            <td>
                                @item.Name
                            </td>
                            <td>
                                <a class="btn btn-danger" href="/teambuilder/delete/@item.Id" title="Remove">Remove</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <a href="/teambuilder/generate" class="btn btn-default">Generate Teams</a>
    }

    @if (Model.BlueTeam.Players.Any() && Model.RedTeam.Players.Any())
    {
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Role</th>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.RedTeam.Players)
                {
                    <tr class="danger">
                        <td>
                            @item.Id
                        </td>
                        <td>
                            @item.Role
                        </td>
                        <td>
                            @item.Name
                        </td>
                    </tr>
                }
                @foreach (var item in Model.BlueTeam.Players)
                {
                    <tr class="info">
                        <td>
                            @item.Id
                        </td>
                        <td>
                            @item.Role
                        </td>
                        <td>
                            @item.Name
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <a href="/teambuilder/reset" class="btn btn-danger">Reset</a>
    }
</section>